title: Patrick Oline # your name (or website title) here
logo: "/images/Screen Shot 2023-01-13 at 11.59.39 AM.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analytics professional with background utilizing Python, SQL, 
  Tableau for the entire data analysis workflow including data wrangling, 
  data storytelling, data visualization, exploratory data analysis, 
  and applying machine learning models to big data.
  <br>
  Coming from a background in teaching mathematics and the sciences, 
  I know the value of communicating key insights in a way that is accessible for all. 
  I've witnessed the difference in how my students understand the delicate issues of 
  mathematics and science based on how it was explained to them.
  <br>
  <br><br>
  <a href="https://www.linkedin.com/in/patrick-oline/">View My LinkedIn Profile</a> 
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
