title: Patrick Oline # your name (or website title) here
logo: "/images/Screen Shot 2023-01-13 at 11.59.39 AM.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>
  This is my Profile!
  <br>
  Second description 
  <br>
  Here are some more words!
  <br><br>
  <a href="https://www.linkedin.com/in/patrick-oline/">View My LinkedIn Profile</a> 
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
